name: Autotag

on:
  push:
    branches:
      - main
      - master

env:
  # Zwingt den Runner, Node 24 für JS-Actions zu nutzen (Zukunftssicherheit)
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  autotag:
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.create_tag.outputs.tag_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # WICHTIG: Lädt die ganze Historie inkl. aller Tags herunter!

    - name: Identify version
      id: read_version
      run: |
        cd ./src
        echo "Identifying version..."
        VERSION=$(jq -r '.version' manifest.json)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        cd ../
        
    - name: Check if tag exists
      id: check_tag
      run: |
        VERSION=${{ steps.read_version.outputs.version }}
        if git rev-parse "$VERSION" >/dev/null 2>&1; then
          echo "Tag $VERSION already exists."
          echo "tag_exists=true" >> $GITHUB_OUTPUT
        else
          echo "Tag $VERSION does not exist."
          echo "tag_exists=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v6.2.0
      
